#https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/types.go
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
#evictionHard:
#  memory.available:  "1024Mi"
failSwapOn: false
serverTLSBootstrap: true

authentication:
  anonymous:
    enabled: false
  x509:
    clientCAFile: /certs/kubernetes-ca-bundle.crt